import { User, Stream, ChatMessage, Notification } from '../types';

export const mockCurrentUser: User = {
  id: 'current-user',
  username: 'john_doe',
  displayName: 'John Doe',
  email: 'john@example.com',
  avatar: 'https://i.pravatar.cc/150?img=8',
  bio: 'Live streamer | Content creator | Gaming enthusiast 🎮',
  nationality: 'USA',
  languages: ['English', 'Spanish'],
  followers: 5432,
  following: 234,
  birthday: '1995-05-15',
  createdAt: new Date('2023-01-15'),
};

export const mockUsers: User[] = [
  {
    id: 'user-1',
    username: 'alex_gamer',
    displayName: 'Alex Gaming',
    email: 'alex@example.com',
    avatar: 'https://i.pravatar.cc/150?img=1',
    bio: 'Professional gamer and streamer 🎮 | FPS specialist',
    nationality: 'Canada',
    languages: ['English', 'French'],
    followers: 125430,
    following: 156,
    isStreaming: true,
    createdAt: new Date('2022-03-10'),
  },
  {
    id: 'user-2',
    username: 'sarah_music',
    displayName: 'Sarah Music',
    email: 'sarah@example.com',
    avatar: 'https://i.pravatar.cc/150?img=5',
    bio: 'Singer songwriter 🎵 | Live performances every night',
    nationality: 'UK',
    languages: ['English'],
    followers: 258760,
    following: 432,
    isStreaming: true,
    createdAt: new Date('2021-11-22'),
  },
  {
    id: 'user-3',
    username: 'chef_master',
    displayName: 'Chef Antonio',
    email: 'chef@example.com',
    avatar: 'https://i.pravatar.cc/150?img=2',
    bio: 'Michelin star chef 👨‍🍳 | Italian cuisine specialist',
    nationality: 'Italy',
    languages: ['English', 'Italian'],
    followers: 87650,
    following: 89,
    isStreaming: true,
    createdAt: new Date('2022-07-08'),
  },
  {
    id: 'user-4',
    username: 'fitness_pro',
    displayName: 'Mike Fitness',
    email: 'fitness@example.com',
    avatar: 'https://i.pravatar.cc/150?img=3',
    bio: 'Personal trainer 💪 | Daily workout streams',
    nationality: 'Australia',
    languages: ['English'],
    followers: 154320,
    following: 201,
    isStreaming: true,
    createdAt: new Date('2022-09-14'),
  },
  {
    id: 'user-5',
    username: 'dance_queen',
    displayName: 'Luna Dance',
    email: 'luna@example.com',
    avatar: 'https://i.pravatar.cc/150?img=9',
    bio: 'Professional dancer 💃 | Hip-hop & Contemporary',
    nationality: 'Brazil',
    languages: ['English', 'Portuguese', 'Spanish'],
    followers: 342100,
    following: 567,
    isStreaming: true,
    createdAt: new Date('2021-05-20'),
  },
  {
    id: 'user-6',
    username: 'tech_wizard',
    displayName: 'David Tech',
    email: 'david@example.com',
    avatar: 'https://i.pravatar.cc/150?img=11',
    bio: 'Coding tutorials 👨‍💻 | Web development & AI',
    nationality: 'India',
    languages: ['English', 'Hindi'],
    followers: 98760,
    following: 234,
    isStreaming: true,
    createdAt: new Date('2022-01-15'),
  },
  {
    id: 'user-7',
    username: 'art_master',
    displayName: 'Sophie Art',
    email: 'sophie@example.com',
    avatar: 'https://i.pravatar.cc/150?img=15',
    bio: 'Digital artist 🎨 | Live painting sessions',
    nationality: 'France',
    languages: ['English', 'French'],
    followers: 67890,
    following: 345,
    isStreaming: true,
    createdAt: new Date('2021-09-30'),
  },
  {
    id: 'user-8',
    username: 'comedy_king',
    displayName: 'Johnny Laughs',
    email: 'johnny@example.com',
    avatar: 'https://i.pravatar.cc/150?img=18',
    bio: 'Stand-up comedian 😂 | Daily comedy shows',
    nationality: 'USA',
    languages: ['English'],
    followers: 456700,
    following: 123,
    isStreaming: true,
    createdAt: new Date('2020-12-01'),
  },
  {
    id: 'user-9',
    username: 'yoga_guru',
    displayName: 'Maya Yoga',
    email: 'maya@example.com',
    avatar: 'https://i.pravatar.cc/150?img=20',
    bio: 'Certified yoga instructor 🧘‍♀️ | Morning sessions',
    nationality: 'Thailand',
    languages: ['English', 'Thai'],
    followers: 123450,
    following: 456,
    isStreaming: true,
    createdAt: new Date('2021-07-10'),
  },
  {
    id: 'user-10',
    username: 'travel_vlogger',
    displayName: 'Tom Explorer',
    email: 'tom@example.com',
    avatar: 'https://i.pravatar.cc/150?img=22',
    bio: 'World traveler ✈️ | Live from 50+ countries',
    nationality: 'Netherlands',
    languages: ['English', 'Dutch', 'German'],
    followers: 234560,
    following: 678,
    isStreaming: true,
    createdAt: new Date('2020-06-15'),
  },
  {
    id: 'user-11',
    username: 'makeup_artist',
    displayName: 'Jessica Beauty',
    email: 'jessica@example.com',
    avatar: 'https://i.pravatar.cc/150?img=25',
    bio: 'Makeup tutorials 💄 | Beauty tips & tricks',
    nationality: 'South Korea',
    languages: ['English', 'Korean'],
    followers: 567890,
    following: 890,
    isStreaming: true,
    createdAt: new Date('2021-03-25'),
  },
  {
    id: 'user-12',
    username: 'pet_lover',
    displayName: 'Emily Pets',
    email: 'emily@example.com',
    avatar: 'https://i.pravatar.cc/150?img=28',
    bio: 'Animal lover 🐕🐈 | Cute pet streams daily',
    nationality: 'Japan',
    languages: ['English', 'Japanese'],
    followers: 345670,
    following: 234,
    isStreaming: true,
    createdAt: new Date('2021-08-18'),
  },
  {
    id: 'user-13',
    username: 'dj_beats',
    displayName: 'DJ Max',
    email: 'djmax@example.com',
    avatar: 'https://i.pravatar.cc/150?img=30',
    bio: 'Electronic music DJ 🎧 | Live sets every weekend',
    nationality: 'Germany',
    languages: ['English', 'German'],
    followers: 432100,
    following: 345,
    isStreaming: true,
    createdAt: new Date('2020-11-11'),
  },
  {
    id: 'user-14',
    username: 'fashion_icon',
    displayName: 'Olivia Style',
    email: 'olivia@example.com',
    avatar: 'https://i.pravatar.cc/150?img=32',
    bio: 'Fashion influencer 👗 | Style tips & hauls',
    nationality: 'Spain',
    languages: ['English', 'Spanish'],
    followers: 678900,
    following: 567,
    isStreaming: true,
    createdAt: new Date('2021-02-14'),
  },
  {
    id: 'user-15',
    username: 'sports_fan',
    displayName: 'Mike Sports',
    email: 'mikesports@example.com',
    avatar: 'https://i.pravatar.cc/150?img=35',
    bio: 'Sports commentator ⚽🏀 | Live match reactions',
    nationality: 'Argentina',
    languages: ['English', 'Spanish'],
    followers: 234500,
    following: 123,
    isStreaming: false,
    createdAt: new Date('2021-06-20'),
  },
];

export const mockStreams: Stream[] = [
  {
    id: 'stream-1',
    title: 'WARZONE WINS ONLY! 🎮🔥',
    thumbnail: 'https://picsum.photos/400/800?random=gaming1',
    viewerCount: 12340,
    streamer: mockUsers[0], // Alex Gaming
    startedAt: new Date(Date.now() - 1000 * 60 * 30),
    category: 'Gaming',
    tags: ['warzone', 'fps', 'competitive'],
    isLive: true,
  },
  {
    id: 'stream-2',
    title: 'Acoustic Covers & Originals 🎸✨',
    thumbnail: 'https://picsum.photos/400/800?random=music1',
    viewerCount: 8920,
    streamer: mockUsers[1], // Sarah Music
    startedAt: new Date(Date.now() - 1000 * 60 * 15),
    category: 'Music',
    tags: ['acoustic', 'guitar', 'covers'],
    isLive: true,
  },
  {
    id: 'stream-3',
    title: 'Authentic Italian Carbonara 🍝👨‍🍳',
    thumbnail: 'https://picsum.photos/400/800?random=cooking1',
    viewerCount: 5670,
    streamer: mockUsers[2], // Chef Antonio
    startedAt: new Date(Date.now() - 1000 * 60 * 45),
    category: 'Cooking',
    tags: ['italian', 'pasta', 'tutorial'],
    isLive: true,
  },
  {
    id: 'stream-4',
    title: 'HIIT Morning Burn 🔥💪',
    thumbnail: 'https://picsum.photos/400/800?random=fitness1',
    viewerCount: 3450,
    streamer: mockUsers[3], // Mike Fitness
    startedAt: new Date(Date.now() - 1000 * 60 * 10),
    category: 'Fitness',
    tags: ['hiit', 'workout', 'morning'],
    isLive: true,
  },
  {
    id: 'stream-5',
    title: 'Hip-Hop Dance Class 💃🎵',
    thumbnail: 'https://picsum.photos/400/800?random=dance1',
    viewerCount: 7890,
    streamer: mockUsers[4], // Luna Dance
    startedAt: new Date(Date.now() - 1000 * 60 * 20),
    category: 'Dance',
    tags: ['hiphop', 'dance', 'tutorial'],
    isLive: true,
  },
  {
    id: 'stream-6',
    title: 'Building a Full-Stack App 👨‍💻',
    thumbnail: 'https://picsum.photos/400/800?random=coding1',
    viewerCount: 4560,
    streamer: mockUsers[5], // David Tech
    startedAt: new Date(Date.now() - 1000 * 60 * 60),
    category: 'Technology',
    tags: ['coding', 'javascript', 'react'],
    isLive: true,
  },
  {
    id: 'stream-7',
    title: 'Digital Portrait Painting 🎨',
    thumbnail: 'https://picsum.photos/400/800?random=art1',
    viewerCount: 2340,
    streamer: mockUsers[6], // Sophie Art
    startedAt: new Date(Date.now() - 1000 * 60 * 35),
    category: 'Art',
    tags: ['digital', 'painting', 'portrait'],
    isLive: true,
  },
  {
    id: 'stream-8',
    title: 'Stand-Up Comedy Hour 😂🎤',
    thumbnail: 'https://picsum.photos/400/800?random=comedy1',
    viewerCount: 15670,
    streamer: mockUsers[7], // Johnny Laughs
    startedAt: new Date(Date.now() - 1000 * 60 * 25),
    category: 'Comedy',
    tags: ['standup', 'comedy', 'funny'],
    isLive: true,
  },
  {
    id: 'stream-9',
    title: 'Morning Yoga Flow 🧘‍♀️☀️',
    thumbnail: 'https://picsum.photos/400/800?random=yoga1',
    viewerCount: 6780,
    streamer: mockUsers[8], // Maya Yoga
    startedAt: new Date(Date.now() - 1000 * 60 * 40),
    category: 'Wellness',
    tags: ['yoga', 'meditation', 'wellness'],
    isLive: true,
  },
  {
    id: 'stream-10',
    title: 'Live from Tokyo! 🗾🎌',
    thumbnail: 'https://picsum.photos/400/800?random=travel1',
    viewerCount: 9870,
    streamer: mockUsers[9], // Tom Explorer
    startedAt: new Date(Date.now() - 1000 * 60 * 55),
    category: 'Travel',
    tags: ['japan', 'tokyo', 'travel'],
    isLive: true,
  },
  {
    id: 'stream-11',
    title: 'Korean Makeup Tutorial 💄✨',
    thumbnail: 'https://picsum.photos/400/800?random=beauty1',
    viewerCount: 11230,
    streamer: mockUsers[10], // Jessica Beauty
    startedAt: new Date(Date.now() - 1000 * 60 * 18),
    category: 'Beauty',
    tags: ['makeup', 'kbeauty', 'tutorial'],
    isLive: true,
  },
  {
    id: 'stream-12',
    title: 'Cute Cats & Dogs Playtime 🐕🐈',
    thumbnail: 'https://picsum.photos/400/800?random=pets1',
    viewerCount: 13450,
    streamer: mockUsers[11], // Emily Pets
    startedAt: new Date(Date.now() - 1000 * 60 * 22),
    category: 'Pets',
    tags: ['cats', 'dogs', 'cute'],
    isLive: true,
  },
  {
    id: 'stream-13',
    title: 'EDM Mix Session 🎧🔊',
    thumbnail: 'https://picsum.photos/400/800?random=dj1',
    viewerCount: 18900,
    streamer: mockUsers[12], // DJ Max
    startedAt: new Date(Date.now() - 1000 * 60 * 50),
    category: 'Music',
    tags: ['edm', 'dj', 'mix'],
    isLive: true,
  },
  {
    id: 'stream-14',
    title: 'Fall Fashion Haul 🍂👗',
    thumbnail: 'https://picsum.photos/400/800?random=fashion1',
    viewerCount: 8760,
    streamer: mockUsers[13], // Olivia Style
    startedAt: new Date(Date.now() - 1000 * 60 * 12),
    category: 'Fashion',
    tags: ['fashion', 'haul', 'style'],
    isLive: true,
  },
];

export const mockChatMessages: ChatMessage[] = [
  {
    id: 'msg-1',
    userId: 'user-1',
    username: 'viewer123',
    message: 'Hey everyone! 👋',
    timestamp: new Date(Date.now() - 1000 * 60 * 5),
  },
  {
    id: 'msg-2',
    userId: 'user-2',
    username: 'gamerfan',
    message: 'This stream is amazing!',
    timestamp: new Date(Date.now() - 1000 * 60 * 4),
  },
  {
    id: 'msg-3',
    userId: 'user-3',
    username: 'musiclover',
    message: 'Love this song! 🎵',
    timestamp: new Date(Date.now() - 1000 * 60 * 3),
  },
  {
    id: 'msg-4',
    userId: 'user-4',
    username: 'supporter',
    message: 'Keep it up! 💪',
    timestamp: new Date(Date.now() - 1000 * 60 * 2),
  },
  {
    id: 'msg-5',
    userId: 'current-user',
    username: 'john_doe',
    message: 'Great content as always!',
    timestamp: new Date(Date.now() - 1000 * 60 * 1),
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'notif-1',
    type: 'follow',
    title: 'New Follower',
    message: 'sarah_music started following you',
    userId: 'user-2',
    read: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 5),
  },
  {
    id: 'notif-2',
    type: 'gift',
    title: 'Gift Received',
    message: 'alex_gamer sent you a Diamond 💎',
    userId: 'user-1',
    read: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 30),
  },
  {
    id: 'notif-3',
    type: 'stream_start',
    title: 'Live Stream',
    message: 'chef_master is now live!',
    userId: 'user-3',
    read: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2),
  },
  {
    id: 'notif-4',
    type: 'follow',
    title: 'New Follower',
    message: 'fitness_pro started following you',
    userId: 'user-4',
    read: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 4),
  },
];